EXEC : main.o functions.o graph.o queue.o stack.o
	gcc -o EXEC main.o functions.o graph.o queue.o stack.o

main.o : main.c
	gcc -c -Wall main.c

functions.o : functions.c
	gcc -c -Wall functions.c

graph.o : graph.c
	gcc -c -Wall graph.c

queue.o : queue.c
	gcc -c -Wall queue.c

stack.o : stack.c
	gcc -c -Wall stack.c